//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uk.JohnCook.dotnet.LTOEncryptionManager.SecureDesktopWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uk.JohnCook.dotnet.LTOEncryptionManager.SecureDesktopWindows.Properties.Resources" +
                            "", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated..
        /// </summary>
        internal static string bip39_validated {
            get {
                return ResourceManager.GetString("bip39_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate/Key error.
        /// </summary>
        internal static string cert_key_error {
            get {
                return ResourceManager.GetString("cert_key_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one word is blank or invalid..
        /// </summary>
        internal static string error_bip39_missing_word {
            get {
                return ResourceManager.GetString("error_bip39_missing_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. Write down the new BIP39 recovery seed and store it securely, then derive the account node..
        /// </summary>
        internal static string recovery_seed_created {
            get {
                return ResourceManager.GetString("recovery_seed_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        internal static string status_calculating {
            get {
                return ResourceManager.GetString("status_calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading window content, which may take a few seconds....
        /// </summary>
        internal static string status_loading_content {
            get {
                return ResourceManager.GetString("status_loading_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing SLIP21 node data....
        /// </summary>
        internal static string status_signing_node {
            get {
                return ResourceManager.GetString("status_signing_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK: TPM-backed certificate exists.
        /// </summary>
        internal static string tpm_cert_found {
            get {
                return ResourceManager.GetString("tpm_cert_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: TPM-backed user certificate (CN=LTO Encryption Manager) does not have a public key.
        /// </summary>
        internal static string tpm_cert_no_pubkey {
            get {
                return ResourceManager.GetString("tpm_cert_no_pubkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: TPM-backed user certificate (CN=LTO Encryption Manager) not found.
        /// </summary>
        internal static string tpm_cert_not_found {
            get {
                return ResourceManager.GetString("tpm_cert_not_found", resourceCulture);
            }
        }
    }
}
